### ISSUE TITLE
Add some package management file to repo

### ISSUE THREAD

**Issue by reckart** [zesch/pydkpro#12]
It would be nice if there would be some file in the repository root which can be used to install all required Python packages with a single command (on any platform, so please not a shell script ;) ).

Also, please document how to get started, i.e.:

* how to set up a virtual environment
* how to install the dependencies
* how to open the examples notebook

**Comment by reckart** [comment]
Might be nice to have the first cell in the examples notebook check if all requirements are installed.

**Comment by aggarwalpiush** [comment]
Thanks for your feedback. Suggested changes will be incorporated soon.

**Comment by aggarwalpiush** [comment]
All suggested changes have been incorporated.
