### ISSUE TITLE
Run Error: Examples UseCases.ipynb

### ISSUE THREAD

**Issue by shoebjoarder** [zesch/pydkpro#17]
Getting an error when trying the UseCases.ipynb

![grafik](https://user-images.githubusercontent.com/28591635/78090707-297f8600-73cb-11ea-87e0-d968132295bd.png)

what to do to fix it?

**Comment by aggarwalpiush** [comment]
Categorize this issue as window directory error as enlisted [here](https://bugs.python.org/issue17023)

Fixed with commit 80399ba

**Comment by shoebjoarder** [comment]
problem still persist
