### ISSUE TITLE
Instruction: requirements.txt not found

### ISSUE THREAD

**Issue by UniDuEChristianGold** [zesch/pydkpro#19]
Install dependencies using pip

$ python -m pip install -r requirements.txt

```ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'```

**Comment by shoebjoarder** [comment]
this instruction needs to be executed in the pydkpro directory after cloning the repository using git.

$ <PATH_TO>\pydkpro>python -m pip install -r requirements1.txt
