### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by UniDuEChristianGold** [zesch/pydkpro#20]
IN [3]:
from pydkpro import Pipeline, Component  
p = Pipeline(version="2.0.0", language='en')
p.add(Component().opennlp_segmenter())
p.add(Component().opennlp_postagger(param_tagset=True))
p.build() 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-cf1fb8c15744> in <module>
----> 1 from pydkpro import Pipeline, Component
      2 p = Pipeline(version="2.0.0", language='en')
      3 p.add(Component().opennlp_segmenter())
      4 p.add(Component().opennlp_postagger(param_tagset=True))
      5 p.build()

~/PyDKPro/pydkpro-master/pydkpro/__init__.py in <module>
      2 
      3 from .cas import Cas
----> 4 from .pipeline import Pipeline, Component
      5 from .typesystems import DKProCoreTypeSystem
      6 from .external import From_spacy, To_spacy, From_nltk, To_nltk, File2str

~/PyDKPro/pydkpro-master/pydkpro/pipeline.py in <module>
      7 import codecs
      8 from generate_basic_pipeline import build_pipeline
----> 9 from dkpro_cli import cliDefinition, killAllRunningContainers
     10 import requests
     11 import json

~/PyDKPro/pydkpro-master/pydkpro/dkpro_cli.py in <module>
      4 
      5 
----> 6 import click      # package for easy cli generation
      7 import subprocess # package to execute the shell,
      8 import re

ModuleNotFoundError: No module named 'click'

**Comment by shoebjoarder** [comment]
fixed with commit eb22fce
