### ISSUE TITLE
ModuleNotFoundError in UseCases 'casis'

### ISSUE THREAD

**Issue by UniDuEChristianGold** [zesch/pydkpro#21]
ModuleNotFoundError: No module named 'cassis'

![image](https://user-images.githubusercontent.com/47823743/79192199-931a7e00-7e28-11ea-9e36-bb04db504494.png)

**Comment by UniDuEChristianGold** [comment]
'cassis' was mentioned in 1 too.
    dkpro-cassis==0.2.7,spacy==2.2.1,nltk==3.4.5 dependecies are not installed properly. Please install them and rerun this jupyter notebook

![image](https://user-images.githubusercontent.com/47823743/79192518-281d7700-7e29-11ea-9856-b15ce4ea07b1.png)

**Comment by UniDuEChristianGold** [comment]
after doing the "Install dependencies using pip" section I run into this message in the jupyter notebook UseCases IN [1]:
spacy==2.2.1 dependecies are not installed properly. Please install them and rerun this jupyter notebook

**Comment by UniDuEChristianGold** [comment]
Terminal:

(base) Christians-MBP:~ c.gold$ cd pydkpro/
(base) Christians-MBP:pydkpro c.gold$ cd pydkpro-master/
(base) Christians-MBP:pydkpro-master c.gold$ python -m pip install -r requirements.txt
Processing /Users/c.gold/Library/Caches/pip/wheels/f3/be/c1/3be420b88892dc94db61d811c1ddcb61be50f81d862ceea149/dkpro_cassis-0.2.7-py3-none-any.whl
Processing /Users/c.gold/Library/Caches/pip/wheels/48/8b/7f/473521e0c731c6566d631b281f323842bbda9bd819eb9a3ead/nltk-3.4.5-py3-none-any.whl
Collecting spacy==2.1.7
  Using cached spacy-2.1.7-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (34.4 MB)
Collecting notebook==6.0.3
  Using cached notebook-6.0.3-py3-none-any.whl (9.7 MB)
Collecting click
  Downloading click-7.1.1-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 974 kB/s 
Collecting yaspin
  Downloading yaspin-0.16.0-py2.py3-none-any.whl (18 kB)
Collecting attrs>=19.3.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting deprecation
  Using cached deprecation-2.0.7-py2.py3-none-any.whl (11 kB)
Collecting more-itertools
  Using cached more_itertools-8.2.0-py3-none-any.whl (43 kB)
Collecting lxml
  Using cached lxml-4.5.0-cp37-cp37m-macosx_10_9_x86_64.whl (4.5 MB)
Collecting sortedcontainers
  Using cached sortedcontainers-2.1.0-py2.py3-none-any.whl (28 kB)
Collecting importlib-resources
  Using cached importlib_resources-1.4.0-py2.py3-none-any.whl (20 kB)
Collecting toposort
  Using cached toposort-1.5-py2.py3-none-any.whl (7.6 kB)
Requirement already satisfied: six in /opt/miniconda3/lib/python3.7/site-packages (from nltk==3.4.5->-r requirements.txt (line 2)) (1.14.0)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.3-cp37-cp37m-macosx_10_6_intel.whl (54 kB)
Requirement already satisfied: numpy>=1.15.0 in /opt/miniconda3/lib/python3.7/site-packages (from spacy==2.1.7->-r requirements.txt (line 3)) (1.18.1)
Collecting plac<1.0.0,>=0.9.6
  Using cached plac-0.9.6-py2.py3-none-any.whl (20 kB)
Collecting srsly<1.1.0,>=0.0.6
  Using cached srsly-1.0.2-cp37-cp37m-macosx_10_9_x86_64.whl (182 kB)
Collecting thinc<7.1.0,>=7.0.8
  Using cached thinc-7.0.8-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.9 MB)
Collecting blis<0.3.0,>=0.2.2
  Using cached blis-0.2.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.0 MB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (34 kB)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/miniconda3/lib/python3.7/site-packages (from spacy==2.1.7->-r requirements.txt (line 3)) (2.22.0)
Collecting preshed<2.1.0,>=2.0.1
  Using cached preshed-2.0.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (145 kB)
Collecting wasabi<1.1.0,>=0.2.0
  Using cached wasabi-0.6.0-py3-none-any.whl (20 kB)
Collecting terminado>=0.8.1
  Using cached terminado-0.8.3-py2.py3-none-any.whl (33 kB)
Collecting jinja2
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 2.6 MB/s 
Collecting Send2Trash
  Using cached Send2Trash-1.5.0-py3-none-any.whl (12 kB)
Processing /Users/c.gold/Library/Caches/pip/wheels/30/0c/26/59ba285bf65dc79d195e9b25e2ddde4c61070422729b0cd914/prometheus_client-0.7.1-py3-none-any.whl
Processing /Users/c.gold/Library/Caches/pip/wheels/7d/14/fa/d88fb5da77d813ea0ffca38a2ab2a052874e9e1142bad0b348/tornado-6.0.4-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting jupyter-core>=4.6.1
  Using cached jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Collecting nbconvert
  Using cached nbconvert-5.6.1-py2.py3-none-any.whl (455 kB)
Collecting traitlets>=4.2.1
  Using cached traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting jupyter-client>=5.3.4
  Downloading jupyter_client-6.1.3-py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 4.4 MB/s 
Collecting ipykernel
  Using cached ipykernel-5.2.0-py3-none-any.whl (117 kB)
Collecting pyzmq>=17
  Using cached pyzmq-19.0.0-cp37-cp37m-macosx_10_9_x86_64.whl (815 kB)
Collecting nbformat
  Using cached nbformat-5.0.5-py3-none-any.whl (170 kB)
Collecting packaging
  Using cached packaging-20.3-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in /opt/miniconda3/lib/python3.7/site-packages (from importlib-resources->dkpro-cassis==0.2.7->-r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /opt/miniconda3/lib/python3.7/site-packages (from importlib-resources->dkpro-cassis==0.2.7->-r requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in /opt/miniconda3/lib/python3.7/site-packages (from thinc<7.1.0,>=7.0.8->spacy==2.1.7->-r requirements.txt (line 3)) (4.42.1)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/miniconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy==2.1.7->-r requirements.txt (line 3)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy==2.1.7->-r requirements.txt (line 3)) (2020.4.5.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/miniconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy==2.1.7->-r requirements.txt (line 3)) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/miniconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy==2.1.7->-r requirements.txt (line 3)) (3.0.4)
Collecting ptyprocess; os_name != "nt"
  Using cached ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp37-cp37m-macosx_10_6_intel.whl (18 kB)
Collecting pygments
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Processing /Users/c.gold/Library/Caches/pip/wheels/63/99/01/9fe785b86d1e091a6b2a61e06ddb3d8eb1bc9acae5933d4740/pandocfilters-1.4.2-py3-none-any.whl
Collecting entrypoints>=0.2.2
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting defusedxml
  Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting bleach
  Using cached bleach-3.1.4-py2.py3-none-any.whl (151 kB)
Collecting testpath
  Using cached testpath-0.4.4-py2.py3-none-any.whl (163 kB)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting ipython>=5.0.0
  Using cached ipython-7.13.0-py3-none-any.whl (780 kB)
Collecting appnope; platform_system == "Darwin"
  Using cached appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Collecting jsonschema!=2.5.0,>=2.4
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.5-py3-none-any.whl (351 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jedi>=0.10
  Using cached jedi-0.16.0-py2.py3-none-any.whl (1.1 MB)
Processing /Users/c.gold/Library/Caches/pip/wheels/9e/56/4f/da13e448a8a5b8671b2954600d5355cf36e557c7aa5020139b/backcall-0.1.0-py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in /opt/miniconda3/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->notebook==6.0.3->-r requirements.txt (line 4)) (45.2.0.post20200210)
Collecting pexpect; sys_platform != "win32"
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Processing /Users/c.gold/Library/Caches/pip/wheels/22/52/11/f0920f95c23ed7d2d0b05f2b7b2f4509e87a20cfe8ea43d987/pyrsistent-0.16.0-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting wcwidth
  Using cached wcwidth-0.1.9-py2.py3-none-any.whl (19 kB)
Collecting parso>=0.5.2
  Downloading parso-0.7.0-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 3.9 MB/s 
Installing collected packages: attrs, pyparsing, packaging, deprecation, more-itertools, lxml, sortedcontainers, importlib-resources, toposort, dkpro-cassis, nltk, cymem, plac, srsly, blis, preshed, wasabi, murmurhash, thinc, spacy, ptyprocess, tornado, terminado, MarkupSafe, jinja2, Send2Trash, prometheus-client, decorator, ipython-genutils, traitlets, jupyter-core, pygments, mistune, pyrsistent, jsonschema, nbformat, pandocfilters, entrypoints, defusedxml, webencodings, bleach, testpath, nbconvert, python-dateutil, pyzmq, jupyter-client, wcwidth, prompt-toolkit, appnope, pickleshare, parso, jedi, backcall, pexpect, ipython, ipykernel, notebook, click, yaspin
Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 appnope-0.1.0 attrs-19.3.0 backcall-0.1.0 bleach-3.1.4 blis-0.2.4 click-7.1.1 cymem-2.0.3 decorator-4.4.2 defusedxml-0.6.0 deprecation-2.0.7 dkpro-cassis-0.2.7 entrypoints-0.3 importlib-resources-1.4.0 ipykernel-5.2.0 ipython-7.13.0 ipython-genutils-0.2.0 jedi-0.16.0 jinja2-2.11.2 jsonschema-3.2.0 jupyter-client-6.1.3 jupyter-core-4.6.3 lxml-4.5.0 mistune-0.8.4 more-itertools-8.2.0 murmurhash-1.0.2 nbconvert-5.6.1 nbformat-5.0.5 nltk-3.4.5 notebook-6.0.3 packaging-20.3 pandocfilters-1.4.2 parso-0.7.0 pexpect-4.8.0 pickleshare-0.7.5 plac-0.9.6 preshed-2.0.1 prometheus-client-0.7.1 prompt-toolkit-3.0.5 ptyprocess-0.6.0 pygments-2.6.1 pyparsing-2.4.7 pyrsistent-0.16.0 python-dateutil-2.8.1 pyzmq-19.0.0 sortedcontainers-2.1.0 spacy-2.1.7 srsly-1.0.2 terminado-0.8.3 testpath-0.4.4 thinc-7.0.8 toposort-1.5 tornado-6.0.4 traitlets-4.3.3 wasabi-0.6.0 wcwidth-0.1.9 webencodings-0.5.1 yaspin-0.16.0
(base) Christians-MBP:pydkpro-master c.gold$ python -m spacy download en_core_web_sm
Collecting en_core_web_sm==2.1.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz (11.1 MB)
     |████████████████████████████████| 11.1 MB 2.9 MB/s 
Building wheels for collected packages: en-core-web-sm
  Building wheel for en-core-web-sm (setup.py) ... done
  Created wheel for en-core-web-sm: filename=en_core_web_sm-2.1.0-py3-none-any.whl size=11074433 sha256=09cbf2102726b7b69fe193951037153ea39a21c24cad6efa5b31741405e7d5cb
  Stored in directory: /private/var/folders/81/h89kf45135z7vpc28762njjc0000gn/T/pip-ephem-wheel-cache-lylvmuru/wheels/59/4f/8c/0dbaab09a776d1fa3740e9465078bfd903cc22f3985382b496
Successfully built en-core-web-sm
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-2.1.0
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
(base) Christians-MBP:pydkpro-master c.gold$ cd Examples/
(base) Christians-MBP:Examples c.gold$ jupyter notebook
[I 08:30:55.352 NotebookApp] Serving notebooks from local directory: /Users/c.gold/pydkpro/pydkpro-master/Examples
[I 08:30:55.352 NotebookApp] The Jupyter Notebook is running at:
[I 08:30:55.352 NotebookApp] http://localhost:8888/?token=ed950a9f1e662bcb0199ff0723a46751d4d095fa4da5a526
[I 08:30:55.352 NotebookApp]  or http://127.0.0.1:8888/?token=ed950a9f1e662bcb0199ff0723a46751d4d095fa4da5a526
[I 08:30:55.352 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:30:55.365 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/c.gold/Library/Jupyter/runtime/nbserver-79931-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=ed950a9f1e662bcb0199ff0723a46751d4d095fa4da5a526
     or http://127.0.0.1:8888/?token=ed950a9f1e662bcb0199ff0723a46751d4d095fa4da5a526
[W 08:31:00.675 NotebookApp] Notebook UseCases.ipynb is not trusted
[W 08:31:00.715 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200414083055 (::1) 11.31ms referer=http://localhost:8888/notebooks/UseCases.ipynb
[I 08:31:01.683 NotebookApp] Kernel started: a81e7277-c70a-4c6c-be1b-40e525ee1d77
[I 08:33:02.515 NotebookApp] Saving file at /UseCases.ipynb
[W 08:33:02.516 NotebookApp] Notebook UseCases.ipynb is not trusted

**Comment by aggarwalpiush** [comment]
@UniDuEChristianGold Could you please elaborate more on the problem you are facing here.

**Comment by shoebjoarder** [comment]
the requirement.txt has been updated in 59ef117 
could you check with the updated file?

**Comment by aggarwalpiush** [comment]
@shoebjoarder does this issue is because of different version of spacy??

**Comment by shoebjoarder** [comment]
> 
> 
> @shoebjoarder does this issue is because of different version of spacy??

not exactly, I saw the dependency mismatch mentioned [here  ](https://github.com/zesch/pydkpro/issues/21#issuecomment-613249710)

> To access the notebook, open this file in a browser:
>     file:///Users/c.gold/Library/Jupyter/runtime/nbserver-79931-open.html
> Or copy and paste one of these URLs:
>     http://localhost:8888/?token=ed950a9f1e662bcb0199ff0723a46751d4d095fa4da5a526
>  or http://127.0.0.1:8888/?token=ed950a9f1e662bcb0199ff0723a46751d4d095fa4da5a526
> ```
> 
> [W 08:31:00.675 NotebookApp] Notebook UseCases.ipynb is not trusted
> [W 08:31:00.715 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200414083055 (::1) 11.31ms referer=http://localhost:8888/notebooks/UseCases.ipynb
> [I 08:31:01.683 NotebookApp] Kernel started: a81e7277-c70a-4c6c-be1b-40e525ee1d77
> [I 08:33:02.515 NotebookApp] Saving file at /UseCases.ipynb
> [W 08:33:02.516 NotebookApp] Notebook UseCases.ipynb is not trusted

regarding this issue, here is a quick fix mentioned in this [link](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#trusting-notebooks)
